services:
  server:
    build: .
    container_name: ecommerce_server
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env.docker
    volumes:
      - ./firebase-credentials.json:/root/firebase-credentials.json:ro